#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH_NAME=`git symbolic-ref HEAD | sed -e 's:^refs/heads/::'`

if test $BRANCH_NAME = master -o $BRANCH_NAME = main -o $BRANCH_NAME = develop; then
  echo "Direct commits to \"${BRANCH_NAME}\" are prohibited."
  exit 1
fi

npm run format
